project:
  name: multiple_sclerosis_archs4_signature
  outdir: outputs/multiple_sclerosis
  workdir: work/multiple_sclerosis
  seed: 42
disease:
  name: multiple_sclerosis
  efo_id: MONDO_0005301
archs4:
  h5_path: data/archs4/human_gene_v2.4.h5
  min_samples_per_group: 3
  max_samples_per_group: 50
  max_series: 5
  case_keywords:
  - multiple sclerosis
  - relapsing remitting multiple sclerosis
  - MS lesion
  - demyelination
  - MS brain
  control_keywords:
  - normal
  - healthy
  - control
  - non-neurological
opentargets:
  min_association_score: 0.1
de:
  method: deseq2
  min_count: 10
  min_samples: 3
meta:
  model: DL
  min_sign_concordance: 0.8
  flag_i2_above: 0.75
signature:
  top_n: 300
  min_de_fdr: 0.5
  weight_formula: meta_z_times_ot_score
