disease:
  name: "peripheral_artery_disease"
  condition: "peripheral arterial disease"

drug_filter:
  include_types:
    - DRUG
    - BIOLOGICAL
  exclude_types:
    - DEVICE
    - PROCEDURE
    - BEHAVIORAL
    - DIETARY_SUPPLEMENT
