disease:
  name: "pulmonary arterial hypertension"
  condition: "pulmonary arterial hypertension"

drug_filter:
  include_types:
    - DRUG
    - BIOLOGICAL
  exclude_types:
    - DEVICE
    - PROCEDURE
    - BEHAVIORAL
    - DIETARY_SUPPLEMENT
