disease:
  name: "takotsubo_cardiomyopathy"
  condition: "Takotsubo cardiomyopathy"

drug_filter:
  include_types:
    - DRUG
    - BIOLOGICAL
  exclude_types:
    - DEVICE
    - PROCEDURE
    - BEHAVIORAL
    - DIETARY_SUPPLEMENT
