disease:
  name: "thoracic_aortic_aneurysm"
  condition: "thoracic aortic aneurysm"

drug_filter:
  include_types:
    - DRUG
    - BIOLOGICAL
  exclude_types:
    - DEVICE
    - PROCEDURE
    - BEHAVIORAL
    - DIETARY_SUPPLEMENT
