disease:
  name: "venous thromboembolism"
  condition: "venous thromboembolism"

drug_filter:
  include_types:
    - DRUG
    - BIOLOGICAL
  exclude_types:
    - DEVICE
    - PROCEDURE
    - BEHAVIORAL
    - DIETARY_SUPPLEMENT
